/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumList: typeof import('./src/components/albumList.vue')['default']
    ArtistItem: typeof import('./src/components/artistItem.vue')['default']
    AudioBox: typeof import('./src/components/playBarTmp/audioBox.vue')['default']
    Bar: typeof import('./src/components/playBarTmp/bar.vue')['default']
    Comments: typeof import('./src/components/comments.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Empty: typeof import('./src/components/empty.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Lyrics: typeof import('./src/components/lyrics.vue')['default']
    MiniBar: typeof import('./src/components/playBarTmp/miniBar.vue')['default']
    MvList: typeof import('./src/components/mvList.vue')['default']
    NavTop: typeof import('./src/components/navTop.vue')['default']
    PlayBar: typeof import('./src/components/playBarTmp/playBar.vue')['default']
    PlayList: typeof import('./src/components/playList.vue')['default']
    ProgressLine: typeof import('./src/components/progressLine.vue')['default']
    Reply: typeof import('./src/components/reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    SongList: typeof import('./src/components/songList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
